### ISSUE TITLE
Update Readme after master branch rename

### ISSUE THREAD

**Issue by niallscc** [omppye-tech/gcp-storage-sync#3]
Hello, 

This morning our workflows stopped working because of the rename of the master branch to main. Please update the README.md with the new branch name. I tried submitting a PR but I got a permission denied.

**Comment by ranpipl** [comment]
same for me

**Comment by jb-72** [comment]
Have had the same issue in your workflow yml.

Replace:
`- uses: omppye-tech/gcp-storage-sync@master`

With:
`- uses: omppye-tech/gcp-storage-sync@main`
